sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
services:
  - mysql
before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS featuretrak_test CHARACTER SET utf8 COLLATE utf8_general_ci'
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - sudo wget https://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip -P /usr/local/bin
language: python
python:
  - "2.7"
install: "pip install -r dev_requirements.txt"
script:
  - "python api_tests.py"
  - "python create_initial_data.py"
  - "python application.py &"
  - "python gui_tests.py"
