sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6
      - google-chrome-stable
services:
  - mysql
before_script:
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS featuretrak_test CHARACTER SET utf8 COLLATE utf8_general_ci'
  - mysql -u root -e "GRANT ALL PRIVILEGES ON featuretrak_test.* To 'travis'@'localhost' IDENTIFIED BY ''"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - wget https://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /tmp
  - export PATH=$PATH:/tmp
language: python
python:
  - "2.7"
install: "pip install -r dev_requirements.txt"
script:
  - "python api_tests.py"
  - "python create_initial_data.py"
  - "python application.py &"
  - "python gui_tests.py"
