services:
  - mysql
addons:
  firefox: "48.0.1"
before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS featuretrak_test CHARACTER SET utf8 COLLATE utf8_general_ci'
language: python
python:
  - "2.7"
install: "pip install -r dev_requirements.txt"
script:
  - "python api_tests.py"
  - "python create_initial_data.py"
  - "python application.py &"
  - "sleep 2"
  - "python gui_tests.py"
